spring:
  profiles:
    active:
    - dev
---
apring:
  profiles: dev
  application:
    name: microservicecloud-config-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-test
#必须保存为UTF-8的格式